# Generated by Django 4.2.20 on 2025-04-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='bron_count',
            field=models.IntegerField(default=0),
        ),
    ]
